version: "3.8"
services:
  front:
    build:
       context: ./front
       dockerfile: Dockerfile
    container_name: front_c
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true

